- app/contextCreators/createDashboardPageContext.js
- app/contextCreators/createDashboardPageContext.test.js
- app/controller.js
- app/forms/dashboard-manifest.json
- app/forms/dashboards/browser-based.json
- app/routes.js
- app/views/dashboard-page.njk
- app/views/dashboard-page.test.js
- app/views/dashboard-section-row.njk
- integration-tests/fixtures/aBrowserBasedData.json
- integration-tests/fixtures/dashboardWithCompleteSections.json
- integration-tests/fixtures/dashboardWithIncompleteSections.json
- integration-tests/showDashboardPage.test.js
The validation for review is now done on the dashboard.
This PR added the errorSummary to the dashboard page containing all the errors that was returned by the SubmitForReview api call.
> Submit for moderation dashboard

- README.md
- package.json
- added a debug script
- updated the readme to explain how to run and debug the app
> Enabled debug

- app/contextCreators/createErrorForQuestion.js
- app/contextCreators/createErrorForQuestion.test.js
- app/contextCreators/createSectionPageContext.js
- app/contextCreators/createSectionPageContext.test.js
- app/contextCreators/generateFields.js
- app/contextCreators/generateOptions.js
- app/contextCreators/generateOptions.test.js
- app/forms/sections/browsers-supported.json
- app/views/fields/checkbox-options.njk
- app/views/fields/radiobutton-options.njk
- integration-tests/showBrowsersSupportedPage.test.js
- integration-tests/showClientApplicationTypePage.test.js
This PR handles the validation errors for client application type section and the browser-supported section.
> Client application type validation

- azure-pipelines.yml
I've updated the SPN being used for the deployments & changed the docker version as well
> Azure pipelines 30122019

- app/dashboard/subDashboards/browser-based/ui.test.js
- app/dashboard/subDashboards/native-desktop/ui.test.js
- app/dashboard/subDashboards/native-mobile/ui.test.js
- app/dashboard/ui.test.js
- azure-pipelines.yml
meant for this just to be 1 file but also got the relocation of the getLocation functions ... oops
> Turn fail task on failed tests on

- app/pages/section/components/fields/checkbox-options.njk
- app/pages/section/components/fields/combobox-options.njk
- app/pages/section/components/fields/radiobutton-options.njk
https://buyingcatalog.visualstudio.com/Buying%20Catalogue/_workitems/edit/4284
> add question to the start of the question ids

- app/pages/dashboard/manifest.json
- app/pages/dashboard/ui.test.js
- fixtures/dashboardWithCompleteSections.json
- fixtures/dashboardWithIncompleteSections.json
Roadmap section added to the dashboard.
> added roadmap section to the dashboard

- app/pages/authority/section/helpers/transformCsv.js
- app/pages/authority/section/helpers/transformCsv.test.js
> 3681: Transform csv epics

- app.js
- app/pages/authority/dashboard/ui.test.js
- app/routes.js
- app/routes.test.js
- app/styles/_app.scss
- package-lock.json
- package.json
Adds favicon in app so every route has favicon preventing the /favicon.io requests to fail which adds an error log.
https://expressjs.com/en/resources/middleware/serve-favicon.html
(also removed skip epics from ui test)
> 5090: BUG Add serve-favicon package and add to app

- azure-pipelines.yml
Adding tags to ensure builds can be easily identified within the Azure Container Registry
> Adding source tags to builds

- app/pages/common/preview/createPreviewPageContext.js
- app/pages/common/preview/createPreviewPageContext.test.js
Added title to the context which will be picked up by <title> in the main page
> 6248: Add title to preview page

- app/endpoints.js
- app/pages/authority/routes.js
- app/pages/authority/routes.test.js
- app/pages/common/dashboard/controller.js
- app/pages/common/dashboard/controller.test.js
- app/pages/common/preview/controller.js
- app/pages/common/preview/controller.test.js
- app/pages/common/section/controller.js
- app/pages/common/section/controller.test.js
- app/pages/health/ready/getReadyStatus.js
- app/pages/health/ready/getReadyStatus.test.js
- app/pages/supplier/dashboard/subDashboards/controller.js
- app/pages/supplier/dashboard/subDashboards/controller.test.js
- app/pages/supplier/routes.js
- app/pages/supplier/routes.test.js
- package-lock.json
- package.json
Activity: [AB#6353](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6353)
Task: [AB#6386](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6386)
> 6353: Use api functions from BCL

- charts/mp/templates/_helpers.tpl
[AB#6636](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6636)
[AB#7440](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7440)
> Use local repository even when useLocalImage=false

- charts/mp/templates/_helpers.tpl
[AB#7922](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7922)
> merge to master

- app/config.js
- app/includes/footer.test.js
- app/includes/header.njk
- app/includes/manifest.json
- charts/mp/templates/deployment.yaml
- charts/mp/values.yaml
- package-lock.json
- package.json
Story [AB#9069](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9069)
Task [AB#9307](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9307) [AB#9362](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9362)
> updated header and footer

- app/includes/footer.test.js
- app/includes/manifest.json
- package-lock.json
- package.json
Story [AB#9069](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9069)
Task [AB#9444](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9444)
> update header and footer again

- README.md
- app/pages/common/preview/createPreviewPageContext.test.js
- app/pages/common/section/components/section-question.test.js
- app/pages/common/section/helpers/transformSectionData.js
- app/pages/common/section/helpers/transformSectionData.test.js
Story [AB#9725](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9725)
Task [AB#9332](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9332)
> fixed carriage return

- azure-pipelines.yml
Task: [AB#10838](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10838)
Story: [AB#10730](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10730)
> Set ignore warning on push to acr

- app/pages/supplier/section/sections/about-supplier/manifest.json
- app/pages/supplier/section/sections/implementation-timescales/manifest.json
- app/pages/supplier/section/sections/solution-description/manifest.json
- azure-pipelines.yml
Increase limits for the solution summary and implementation detail (timescales) fields. Increase the limit for the supplier description (summary).
Activity: [AB#11064](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11064)
Tasks: [AB#10755](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10755), [AB#11132](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11132)
> Increase character limits

- package-lock.json
- package.json
Activity: [AB#11133](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11133)
Task: [AB#11136](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11136)
> Update to latest component library version

- .gitattributes
- Dockerfile
- README.md
- azure-pipelines.yml
- package-lock.json
- package.json
Update dependencies, use node 14, tidy readme and add .gitattributes
Activities: [AB#11100](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11100), [AB#11133](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11133)
Tasks: [AB#11105](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11105), [AB#11136](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11136)
> Update dependencies and use node 14

- package-lock.json
- package.json
Activity: [AB#11185](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11185)
Task: [AB#11200](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11200)
> Use latest BC packages

- charts/mp/templates/ingress.yaml
Task: [AB#11823](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11823)
Activity: [AB#13202](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13202)
> Ingress configuration updated to v1

- app/common/helpers/routerHelper.js
- app/config.js
- app/pages/authority/routes.js
- app/pages/error/template.njk
- app/pages/supplier/routes.js
- app/routes.js
- app/routes.test.js
Ticket: [AB#14275](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14275)
Story: [AB#14240](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14240)
> Improve error message

- app/manifestProvider.js
- package-lock.json
- package.json
Activity: [AB#14613](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14613)
Task: [AB#14690](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14690)
> Address uncontrolled data in path

- app/includes/__snapshots__/footer.test.js.snap
- package-lock.json
- package.json
Ticket: [AB#14636](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14636)
Story: [AB#13179](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13179)
> Update buying catalogue components
